### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by redDwarf03**

### CODE REVIEW

**Comment by redDwarf03** [comment]
Hello
if you are agree, could you publish this PR on pub.dev please

**Comment by knaeckeKami** [comment]
Thanks. Unfortunately, I lost access to the package on pub.dev as I published this with an account of a company that I no longer work with. But you can add it as a git dependency

**Comment by redDwarf03** [comment]
If you are agree, I can add a new lib with new name in pub.dev and precise this lib is deprecated.

**Comment by knaeckeKami** [comment]
sure

**Pull request merged**
